	htp.print('<script type="text/javascript">');

	htp.print('	var requpdate;');
	htp.print('	function loadXMLUpdate(url)');
	htp.print('{');
	htp.print('		window.status="Getting data from server.......";');
	htp.print('		requpdate=null;');
	htp.print('		if (window.XMLHttpRequest && !(window.ActiveXObject) )');
	htp.print('  {// code for Firefox, Opera, IE7, etc.');
	htp.print('    	try {');
	htp.print('			requpdate = new XMLHttpRequest();');
	htp.print('        } catch(e) {');
	htp.print('			requpdate = false;');
	htp.print('       }');
	htp.print('  }');
	htp.print('		else if (window.ActiveXObject)');
	htp.print('  {// code for IE6, IE5');
	htp.print('      	try {');
	htp.print('  			requpdate = new ActiveXObject("Msxml2.XMLHTTP");');
	htp.print('        } catch(e) {');
	htp.print('       	try {');
	htp.print('         		requpdate = new ActiveXObject("Microsoft.XMLHTTP");');
	htp.print('        	} catch(e) {');
	htp.print('          		requpdate = false;');
	htp.print('       	}');
	htp.print('		}');
	htp.print('  }');
	htp.print('		if (requpdate!=null)');
	htp.print('  {');
	htp.print('  			requpdate.onreadystatechange=function(){processReqUpdate();}');
	htp.print('  			requpdate.open("POST",url,true);');
	htp.print(' 			requpdate.send(null);');	
	htp.print('		        window.status="Done";');
	htp.print('  }');
	htp.print('		else'				);
	htp.print('  {');
	htp.print('  		alert("Your browser does not support XMLHTTP.");');
	htp.print('  }');
	htp.print('}');	
	
	htp.print('function processReqUpdate() {');
	htp.print('// only if requpdate shows "loaded"');
	htp.print('if (requpdate.readyState == 4) {');
	htp.print('// only if "OK"');
	htp.print('if (requpdate.status == 200) {');
	htp.print('// ...processing statements go here...');
	htp.print('		eval(requpdate.responseText);');		
	htp.print('		window.status="Done";');
	htp.print('} else {');
	htp.print('  alert("There was a problem retrieving the XML data:\n" +');
	htp.print('      requpdate.statusText);');
	htp.print(' }');
	htp.print('}');
	htp.print('}');	

	htp.print('	var req;');
	htp.print('	var v_div;');
	htp.print('function AssignData(url,vdiv)');
	htp.print('{');
	htp.print('	v_div = vdiv;');
	htp.print('		window.status="Getting data from server.......";');
	htp.print('		req=null;');
	htp.print('		if (window.XMLHttpRequest && !(window.ActiveXObject) )');
	htp.print('  {// code for Firefox, Opera, IE7, etc.');
	htp.print('    	try {');
	htp.print('			req = new XMLHttpRequest();');
	htp.print('        } catch(e) {');
	htp.print('			req = false;');
	htp.print('       }');
	htp.print('  }');
	htp.print('		else if (window.ActiveXObject)');
	htp.print('  {// code for IE6, IE5');
	htp.print('      	try {');
	htp.print('  			req = new ActiveXObject("Msxml2.XMLHTTP");');
	htp.print('        } catch(e) {');
	htp.print('       	try {');
	htp.print('         		req = new ActiveXObject("Microsoft.XMLHTTP");');
	htp.print('        	} catch(e) {');
	htp.print('          		req = false;');
	htp.print('       	}');
	htp.print('		}');
	htp.print('  }');
	htp.print('		if (req!=null)');
	htp.print('  {');
	htp.print('  			req.onreadystatechange=function(){processReqChange();}');
	
	htp.print('  			req.open("POST",url,true);');
	htp.print(' 			req.send(null);');	
	htp.print('		        window.status="Done";');
	htp.print('  }');
	htp.print('		else'				);
	htp.print('  {');
	htp.print('  		alert("Your browser does not support XMLHTTP.");');
	htp.print('  }');
	htp.print('}');	
	
	htp.print('function processReqChange() {');
	htp.print('// only if req shows "loaded"');
	
	htp.print('if (req.readyState == 4) {');
	htp.print('// only if "OK"');
	htp.print('if (req.status == 200) {');
	htp.print('// ...processing statements go here...');
	htp.print('		displayMessages(req.responseText);');		
	htp.print('		window.status="Done";');
	htp.print('} else {');
	htp.print('  alert("There was a problem retrieving the XML data:\n" +');
	htp.print('      displayErrors(req.statusText);');
	
	htp.print(' }');
	htp.print('}');
	htp.print('}');	
	
	htp.print('// function that displays an error message');
	htp.print('function displayErrors(message)');
	htp.print('{');
  	htp.print('// display error message, with more technical details if debugMode is true');
  	htp.print('     displayMessages("Error accessing the server! ",v_div);');
  	htp.print('}');
  	
  	htp.print('// displays a message');
	htp.print('function displayMessages(v_message)');
	htp.print('{');
	htp.print('	var assigndiv = document.getElementById(v_div);');
	htp.print('	assigndiv.innerHTML = v_message;');
	htp.print('}');

	
	htp.print('function getValXML(url)');
	htp.print('{');
	htp.print('var http = false;');
	htp.print('if (window.XMLHttpRequest && !(window.ActiveXObject) )');
	htp.print('  {// code for Firefox, Opera, IE7, etc.');
	htp.print('    	try {');
	htp.print('		http = new XMLHttpRequest();');
	htp.print('        } catch(e) {');
	htp.print('			http = false;');
	htp.print('       }');
	htp.print('  }');
	htp.print('		else if (window.ActiveXObject)');
	htp.print('  {// code for IE6, IE5');
	htp.print('      	try {');
	htp.print('  			http = new ActiveXObject("Msxml2.XMLHTTP");');
	htp.print('        } catch(e) {');
	htp.print('       	try {');
	htp.print('         		http = new ActiveXObject("Microsoft.XMLHTTP");');
	htp.print('        	} catch(e) {');
	htp.print('          		http = false;');
	htp.print('       	}');
	htp.print('		}');
	htp.print('  }');
	htp.print('  http.open("POST", url, false); ');
	htp.print('  http.send(null);');
	htp.print('  var result = http.responseText;');
	htp.print('  return result.substring(0,result.length-1);'); 
	htp.print('}');
	
	htp.print('</script>');		
